/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/Alien.gltf -o src/components/models/Alien.jsx -r public/
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, useAnimations, useCursor } from '@react-three/drei'

export function Alien(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Alien.gltf')
  const { actions } = useAnimations(animations, group)
  const [hovered, setHovered] = useState(false)

  useCursor(hovered);

  useEffect(() => {
    actions['Idle'].reset().fadeIn(0.5).play();
    return () => actions['Idle'].fadeOut(0.5)
  }, [])

  useEffect(() => {
    if (hovered) {
      actions['Dance'].reset().fadeIn(0.5).play();
      return () => actions['Dance'].fadeOut(0.5)
    }
  }, [hovered])

  return (
    <group ref={group} {...props} dispose={null} onPointerOver={() => setHovered(true)} onPointerLeave={() => setHovered(false)}>
      <group name="Scene">
        <group name="MonsterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <skinnedMesh name="Alien" geometry={nodes.Alien.geometry} material={materials.Texture} skeleton={nodes.Alien.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Alien.gltf')
