/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/Bat.gltf -o src/components/models/Bat.jsx -r public/
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Bat(props) {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Bat.gltf')
  const { actions } = useAnimations(animations, group)
  const [hovered, setHovered] = useState(false)

  useEffect(() => {
    actions['Flying'].reset().fadeIn(0.5).play();
    return () => actions['Flying'].fadeOut(0.5)
  }, [])

  useEffect(() => {
    console.log('hovered', hovered)
    if (hovered) {
      actions['Bite_Front'].reset().fadeIn(0.5).play();
      return () => actions['Bite_Front'].fadeOut(0.5)
    }
  }, [hovered])
  return (
    <group ref={group} {...props} dispose={null} onPointerOver={() => setHovered(true)} onPointerLeave={() => setHovered(false)}>
      <group name="Scene">
        <group name="MonsterArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Head} />
          <skinnedMesh name="Bat002" geometry={nodes.Bat002.geometry} material={materials.Texture} skeleton={nodes.Bat002.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Bat.gltf')
